### ISSUE TITLE
OrderedTabularInline move_up_down_links() fails when order_with_respect_to has non-standard primary_key

### ISSUE THREAD

**Issue by shuckc** [bfirsh/django-ordered-model#127]
I'm working on a case of missing up/down links on an `OrderedTabularInline` caused by an error thrown from `move_up_down_links`:

```
Traceback (most recent call last):
  File "C:\Users\cshucks\repos\abfw-app\venv\lib\site-packages\ordered_model\admin.py", line 253, in move_up_down_links
    r = self._move_up_down_links(obj)
  File "C:\Users\cshucks\repos\abfw-app\venv\lib\site-packages\ordered_model\admin.py", line 280, in _move_up_down_links
    if value.__class__ is self.parent_model and value is not None and value.id is not None]
AttributeError: 'Account' object has no attribute 'id'
```

The class with which we are ordering with respect to (Account) has a custom primary key:
```
class Account(models.Model):
    acc = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=100)
    ...

class OrderFormLine(OrderedModel):
    acc = models.ForeignKey(hello.models.Account)
    bin_no = models.CharField(max_length=20)
    title = models.CharField(max_length=50, blank=True)
    ...

```
Which trips up [this code](https://github.com/bfirsh/django-ordered-model/blob/0d6ae776e48802dafc6bb5af1fcde33146b33ef0/ordered_model/admin.py#L265):
```
        order_with_respect_to = obj._get_order_with_respect_to() or []  # [(u'acc', <Account: Z1>)]
        parent_model = self.parent_model._meta  # hello.account

        fields = [
            str(value.id) for field_name, value in order_with_respect_to
            if value.__class__ is self.parent_model and value is not None and value.id is not None]
```
Changing it to use `value.pk` works - I'll prepare a pull request

**Comment by shuckc** [comment]
Just ran the tests and nothing seems to break:
```
chris@chris-b ~/repos/django-ordered-model $ ./script/test
Sending build context to Docker daemon  316.4kB
Step 1/5 : FROM python:2.7
 ---> fa8e55b2235d
Step 2/5 : WORKDIR /code
 ---> Using cache
 ---> 6080d60fe0d1
Step 3/5 : ADD requirements.txt /code/requirements.txt
 ---> Using cache
 ---> 458f83e4341b
Step 4/5 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 62a19fa6d73c
Step 5/5 : ADD . /code
 ---> Using cache
 ---> 032b0fac3c45
Successfully built 032b0fac3c45
Successfully tagged django-ordered-model:latest
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 0.479s

OK
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
Destroying test database for alias 'default'...
```

**Comment by bfirsh** [comment]
Thanks! I'll push out a release.
