### ISSUE TITLE
bug bulk_create

### ISSUE THREAD

**Issue by nimasalemahim** [bfirsh/django-ordered-model#230]
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/nima/.virtualenvs/behtarino/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 946, in add
    through_defaults=through_defaults,
  File "/home/nima/.virtualenvs/behtarino/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 1150, in _add_items
    ])
TypeError: bulk_create() got an unexpected keyword argument 'ignore_conflicts'

this is error i get in bulk_create method i think there is a problem in overiding this method in OrderdModel
can you help me this is bug or some thing else ?

**Comment by JanMalte** [comment]
Seems like this argument is missing here:
`ordered_model.models.OrderedModelQuerySet.bulk_create`

**Comment by JanMalte** [comment]
There is already an MR for this issue #228

**Comment by shuckc** [comment]
Fixed by merge of #235, thanks for the report
