### ISSUE TITLE
Cannot save instances when the model inherits both from OrderedModel and PolymorphicModel

### ISSUE THREAD

**Issue by jajakobyly** [bfirsh/django-ordered-model#44]
Hi,

I am currently playing with django-ordered-model and also django-polymorphic. I have created a, rather simple, model:

```python
class CourseItem(PolymorphicModel, OrderedModel, VisibleModel):
    name = models.CharField(max_length=100, verbose_name=_('item name'))

    item_group = models.ForeignKey(CourseItemGroup, related_name='items', verbose_name=_('item group'))

    order_with_respect_to = 'item_group'

    def __str__(self):
        return self.name

    class Meta(OrderedModel.Meta):
        verbose_name = _('course item')
        verbose_name_plural = _('course items')
```

The problem is, I cannot save instances of this model: I get following exception:

```python
Traceback (most recent call last):
  File "[...]\tests\tests\test_courses\test_course_item.py", line 8, in test___str__
    item = CourseItemFactory(name='foo')
  File "[...]\env\lib\site-packages\factory\base.py", line 82, in __call__
    return cls.create(**kwargs)
  File "[...]\env\lib\site-packages\factory\base.py", line 585, in create
    return cls._generate(True, attrs)
  File "[...]\env\lib\site-packages\factory\base.py", line 510, in _generate
    obj = cls._prepare(create, **attrs)
  File "[...]\env\lib\site-packages\factory\base.py", line 485, in _prepare
    return cls._create(model_class, *args, **kwargs)
  File "[...]\env\lib\site-packages\factory\django.py", line 153, in _create
    return manager.create(*args, **kwargs)
  File "[...]\env\lib\site-packages\django\db\models\manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[...]\env\lib\site-packages\django\db\models\query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "[...]\env\lib\site-packages\polymorphic\polymorphic_model.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "[...]\env\lib\site-packages\ordered_model\models.py", line 40, in save
    c = self.get_ordering_queryset().aggregate(Max('order')).get('order__max')
  File "[...]\env\lib\site-packages\ordered_model\models.py", line 31, in get_ordering_queryset
    qs = qs or self._default_manager.all()
  File "[...]\env\lib\site-packages\django\db\models\manager.py", line 206, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % type.__name__)
AttributeError: Manager isn't accessible via CourseItem instances
```

I have figured out, that the problem sits in `OrderedModel.get_ordering_queryset` in this line:

```python
qs = qs or self._default_manager.all()
```

After some googling I have found [this StackOverflow answer](http://stackoverflow.com/a/10111121/3657395); the 2nd comment proposes to use `__class__.objects` instead of `_default_manager` and after the change everything automagically started to work. I am not a Django expert, so I cannot say why this works, but it works :) 

I will fill a pull request in a moment with this patch soon.

**Comment by jajakobyly** [comment]
My factory and test if needed:
```python
# Factory
class CourseItemFactory(factory.DjangoModelFactory):
    class Meta:
        model = CourseItem

    name = factory.Sequence(lambda n: 'Item {}'.format(n))
    item_group = factory.SubFactory(CourseItemGroupFactory)


# Test
class CourseItemTestCase(TestCase):
    def test___str__(self):
        item = CourseItemFactory(name='foo')
        self.assertEqual(str(item), 'foo')
```
