### ISSUE TITLE
Unicode string literal prefix breaks Python 3.2

### ISSUE THREAD

**Issue by jrschneider** [bfirsh/django-ordered-model#62]
It appears that the Unicode string literal prefixes break Python 3.2 (where support for the u'' prefix was removed). For Python >3.2, PEP 414 makes the Unicode string literal available again.

Django 1.8 officially supports Python >= 3.2, so support for this version of Python would be advisable. 

Virtualenv Freeze List:
Django==1.8.6
daemonize==2.4.1
django-ordered-model==0.4.2
djangorestframework==3.3.1
wsgiref==0.1.2

Python 3.2.3
OS: Raspbian (Raspberry Pi Linux rpi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux)

Works fine under Python 2.7 on the RPi and Ubuntu 14.04LTS (Python 3.4.3). I believe Debian Jessie ships with 3.2 as it's default implementation for Python 3.X. 

I'm compiling 3.4.3 manually on the RPi for my own use with this library, but I suspect that won't be an issue.

Given that there is an outstanding issue for adding tests into Travis CI (#27), I would expect at that point for this issue to be illuminated.

If support for Python 3.2 is not desired, feel free to close the issue. I'm working around it by upgrading the Python version I'm using manually.

```python
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/lib/python3.2/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/lib/python3.2/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/lib/python3.2/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/lib/python3.2/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/build/django/django/contrib/admin/apps.py", line 22, in ready
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/build/django/django/contrib/admin/__init__.py", line 24, in autodiscover
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/lib/python3.2/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.2/importlib/__init__.py", line 124, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 821, in _gcd_import
    loader.load_module(name)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 436, in load_module
    return self._load_module(fullname)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 141, in decorated
    return fxn(self, module, *args, **kwargs)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 330, in _load_module
    code_object = self.get_code(name)
  File "/usr/lib/python3.2/importlib/_bootstrap.py", line 413, in get_code
    dont_inherit=True)
  File "/var/lib/storage/virtualenv/wrccdc-temp-py3/lib/python3.2/site-packages/ordered_model/admin.py", line 78
    move_up_down_links.short_description = _(u'Move')
                                                   ^
SyntaxError: invalid syntax
```

**Comment by bfirsh** [comment]
This work alright for you? https://github.com/bfirsh/django-ordered-model/tree/unicode-literals

**Comment by timgraham** [comment]
About Python 3.2 -- Django 1.8 will drop official support at the end of 2016 as Python 3.2 is now end-of-life. Patch looks good to me regardless.

**Comment by jrschneider** [comment]
Well, 3.2 is officially dead this month. My 3.2 version of pip has been updated and is now breaking when I try to install the latest version of pretty much anything, so I can't do any testing. Django is pretty close to  dropping support for it, and it works fine for newer versions of Python, so I don't see any purpose in keeping this issue open.
